name: Compile client

on: push

jobs: 
  heckdustry:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Настройка JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Настройка ANDROID_HOME
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH

    - name: Настройка разрешений
      run: chmod +x ./gradlew

    - name: Упаковка спрайтов
      run: ./gradlew pack

    - name: Компиляция версии для ПК
      run: ./gradlew desktop:dist

    - name: Компиляция версии для Android
      run: ./gradlew android:assembleDebug  

    - name: Выгрузка Desktop
      uses: actions/upload-artifact@v2
      with:
        name: Desktop

        path: desktop/build/libs/Mindustry.jar

    - name: Выгрузка Android
      uses: actions/upload-artifact@v2
      with:
        name: Android

        path: android/build/outputs/apk/*
